### ISSUE TITLE
Publish on Flathub

### ISSUE THREAD

**Issue by Newbytee** [SlyFabi/WSysMon#1]
Hi! It would be nice to have this app packaged and published on Flathub. Feel free to ask if you have any questions about doing this.

**Comment by JakobDev** [comment]
This is not possible. Flatpak Apps run inside a Sandbox. It is currently not possible for a Task manager to run inside a Flatpak.

**Comment by SlyFabi** [comment]
@JakobDev is right. This is sadly not possible due to the sandbox restrictions.
