### ISSUE TITLE
Strange Total RAM value

### ISSUE THREAD

**Issue by bigbn** [SlyFabi/WSysMon#11]
I have 16Gb single slot inserted. For some reason `WSysMon` displaying **17GB (16.58)**, when `htop` result is **15.4**,  and `windows` shows it as is just **16(15.9)**.

![linram](https://user-images.githubusercontent.com/740864/187021958-f573f63f-ca02-4ea6-aa92-fc242a9d25f2.png)
![winram](https://user-images.githubusercontent.com/740864/187021972-54c30870-449e-41f3-b6c0-d12cb3ed2c3e.jpg)

**Comment by SlyFabi** [comment]
This is correct behavior. It uses SI units by default, but with https://github.com/SlyFabi/WSysMon/commit/35ee4c507feb42e2ab1f334d2bc289255a4d85c1 you can change that.
