### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EysseW** [SlyFabi/WSysMon#2]

**Comment by EysseW** [comment]
Oops, I clicked enter :)
Anyway,
After building I got:
```
❯ ./WSysMon

(WSysMon:211260): Gtk-WARNING **: 19:29:18.924: Theme parsing error: gtk.css:19154:28: Junk at end of value for background-color
fish: Job 1, './WSysMon' terminated by signal SIGSEGV (Address boundary error)
```

From the binary, I got the exact same error.

As for dependencies, I got these for libprocps:
```
❯ yay libpro
15 aur/libproxmox-backup-qemu0-dev-bin 1.3.1-1 (+0 0.00) 
    
14 aur/libproxmox-backup-qemu0-bin 1.3.1-1 (+0 0.00) 
    
13 aur/libproj4-projcompathack 4.9.3-1 (+0 0.00) 
    Cartographic Projections library, libraries only. Legacy version 4.x. Hack to be compatible with newer proj. Might not work fully, there to fulfill dependency for other legacy packages like perl-geo-proj4.
12 aur/libprotoident 2.0.14-1 (+0 0.00) (Out-of-date: 2021-12-11) 
    Network traffic classification library that requires minimal application payload
11 aur/libprotothread-git r47.3c1ed2e-1 (+0 0.00) 
    programming model that combines the advantages of event-driven programming and threaded programming
10 aur/lib32-libprotobuf-git v3.3.1.r420.gd1bc27ca-1 (+3 0.00) (Orphaned) (Out-of-date: 2022-05-07) 
    A language-neutral, platform-neutral extensible mechanism for serializing structured data.
9 aur/libprotobuf2 2.6.1-1 (+14 0.00) (Orphaned) 
    Protocol Buffers Library 2 - provides protobuf2 library for protobuf3 installations
8 multilib/lib32-procps-ng 3.3.17-1 (32.3 KiB 81.6 KiB) (Installed)
    Utilities for monitoring your system and its processes (32-bit)
7 multilib/lib32-libproxy 0.4.18-1 (74.3 KiB 217.8 KiB) (Installed)
    Automatic proxy configuration management library (32-bit)
6 extra/protobuf-c 1.4.1-1 (106.3 KiB 318.0 KiB) (Installed)
    Protocol Buffers implementation in C
5 extra/protobuf 21.4-1 (2.0 MiB 8.9 MiB) (Installed)
    Protocol Buffers - Google's data interchange format
4 extra/libproxy-webkit 0.4.18-1 (11.7 KiB 30.0 KiB) 
    JavaScriptCore-based PAC proxy support for libproxy
3 extra/libproxy 0.4.18-1 (86.6 KiB 301.2 KiB) (Installed)
    Automatic proxy configuration management library
2 extra/gperftools 2.10-1 (693.8 KiB 2.8 MiB) (Installed)
    Fast, multi-threaded malloc and nifty performance analysis tools
1 core/procps-ng 3.3.17-1 (516.6 KiB 1.5 MiB) (Installed)
    Utilities for monitoring your system and its processes
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 
```
and these for libgtkmm:
```
❯ yay libgtkmm
2 extra/gtkmm3 3.24.6-1 (1.4 MiB 9.3 MiB) (Installed)
    C++ bindings for GTK+ 3
1 extra/gtkmm-4.0 4.6.1-1 (1.3 MiB 8.6 MiB) (Installed)
    C++ bindings for GTK 4
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 
```

**Comment by SlyFabi** [comment]
Please try again with the latest master commit. If this doesn´t fix it, I´ll need a coredump.

**Comment by EysseW** [comment]
same issue :(

**Comment by SlyFabi** [comment]
Could you run `gdb ./WSysMon` , then `run` and give me the output ? When it´s built from source it should give a pretty clear output to what´s happening.

**Comment by EysseW** [comment]
Did that! Got: ```
> gdb ./WSysMon          
                                                                                  ─╯
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./WSysMon...
(gdb) run
Starting program: /home/rat/.gits/WSysMon/build/WSysMon 
    
       /\         rat@arch
      /  \        os     Arch Linux
     /\   \       host   x86_64
    /      \      kernel 5.19.2-xanmod1-1-x64v2
   /   ,,   \     uptime 1h 20m
  /   |  |  -\    pkgs   2314
 /_-''    ''-_\   memory 3088M / 15929M

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff29ff6c0 (LWP 75473)]
[New Thread 0x7ffff21fe6c0 (LWP 75474)]
[New Thread 0x7ffff19fd6c0 (LWP 75475)]
[New Thread 0x7ffff11fc6c0 (LWP 75477)]

(WSysMon:75383): Gtk-WARNING **: 19:44:49.121: Theme parsing error: gtk.css:19154:28: Junk at end of value for background-color

Thread 1 "WSysMon" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ed6ad4 in Gdk::Monitor::get_workarea(Gdk::Rectangle&) const () from /usr/lib/libgdkmm-3.0.so.1
(gdb) 
```

**Comment by EysseW** [comment]
I'd like to add to the entire thing that I installed the package from the AUR now and it seems to be working perfectly!

**Comment by SlyFabi** [comment]
This bug was fixed in a previous commit.
