### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by dasmikko** [SlyFabi/WSysMon#4]
I'm trying to build, and I get this error, when running `cmake --build ./build --config Release`

```
In file included from /home/username/w/WSysMon/src/ui/views/ProcessesView.cpp:2:
/home/username/w/WSysMon/src/ui/views/../../api/process/ProcessManager.h:8:10: fatal error: proc/readproc.h: No such file or directory
    8 | #include <proc/readproc.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/WSysMon.dir/build.make:132: CMakeFiles/WSysMon.dir/src/ui/views/ProcessesView.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/WSysMon.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

Deps are installed.

**Comment by SlyFabi** [comment]
You probably forgot to install libprocps-dev or -devel depending on your distro.

**Comment by LordOfTheWeebs** [comment]
I actually had the exact same error show up. I'm on an Arch system and building from a direct clone here and the AUR package of this program both fail.

Looking up the readproc.h not found issue in a more general context, it seems as though either procps-ng fucked something up or readproc.h hasn't been in procps in general for a while. I'm not a programmer, though, so I wouldn't know. [This is the most recent issue I could find that cites the same readproc.h not found error](https://github.com/opentrack/opentrack/issues/1453). Hopefully this helps in some way.

**Comment by SlyFabi** [comment]
Fixed in https://github.com/SlyFabi/WSysMon/commit/c2b362201e5c535c81902cfb71a71bcfbab0b0ed Turns out procps was some leftover code. Oh well...
