### ISSUE TITLE
Add ability to monitor Intel and amd gpus

### ISSUE THREAD

**Issue by vgarleanu** [SlyFabi/WSysMon#5]
This program has the ability to get stats on a nvidia gpu but it not Intel or amd gpus. It would be ideal if you could get statistics on other gpus.

**Comment by SlyFabi** [comment]
https://github.com/SlyFabi/WSysMon/commit/7bf1293b589cd27407a255bbde38954c869ce80f should add support for it. If you have an Intel or AMD GPU it would be really helpful if you could test it.

**Comment by pa-sowa** [comment]
I tested https://github.com/SlyFabi/WSysMon/commit/7bf1293b589cd27407a255bbde38954c869ce80f on AMD Ryzen 7 PRO 4750G with Radeon Graphics. It does show GPU usage graph on Performance tab. However the 'Speed' and 'Temperature' values are not populated. Also it does not populate the 'GPU Memory' column on Processes tab.

**Comment by Zardoz89** [comment]
Same here with an AMD RX6600
![imagen](https://user-images.githubusercontent.com/888483/186479472-b17940dd-b2e3-47e8-b042-41dd804b633d.png)
Also, I just noticed the weird Video memory report -> 1GiB of 9GiB , when my card have 8 GiB
